# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

call_rpart_ <- function(formula_obj, wrap_rpart, newdata, weight_vec, classname_map) {
    .Call('_fastAdaboostDoD_call_rpart_', PACKAGE = 'fastAdaboostDoD', formula_obj, wrap_rpart, newdata, weight_vec, classname_map)
}

adaboost_main_loop_ <- function(formula_obj, data_df, nIter, wrap_rpart, vardep, classname_map, boost_method) {
    .Call('_fastAdaboostDoD_adaboost_main_loop_', PACKAGE = 'fastAdaboostDoD', formula_obj, data_df, nIter, wrap_rpart, vardep, classname_map, boost_method)
}

calculate_test_error_ <- function(vardep, predicted_class_int) {
    .Call('_fastAdaboostDoD_calculate_test_error_', PACKAGE = 'fastAdaboostDoD', vardep, predicted_class_int)
}

predict_adaboost_ <- function(tree_list, coeff_vector, newdata, num_examples, wrap_rpart_predict, classnames_map) {
    .Call('_fastAdaboostDoD_predict_adaboost_', PACKAGE = 'fastAdaboostDoD', tree_list, coeff_vector, newdata, num_examples, wrap_rpart_predict, classnames_map)
}

predict_real_adaboost_ <- function(tree_list, coeff_vector, newdata, num_examples, wrap_rpart_predict_real) {
    .Call('_fastAdaboostDoD_predict_real_adaboost_', PACKAGE = 'fastAdaboostDoD', tree_list, coeff_vector, newdata, num_examples, wrap_rpart_predict_real)
}

